// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v5.29.3
// source: triangle.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Point struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Point) Reset() {
	*x = Point{}
	mi := &file_triangle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_triangle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_triangle_proto_rawDescGZIP(), []int{0}
}

func (x *Point) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Point) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

// Clockwise order points
type Triangle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	P1            *Point                 `protobuf:"bytes,1,opt,name=p1,proto3" json:"p1,omitempty"`
	P2            *Point                 `protobuf:"bytes,2,opt,name=p2,proto3" json:"p2,omitempty"`
	P3            *Point                 `protobuf:"bytes,3,opt,name=p3,proto3" json:"p3,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Triangle) Reset() {
	*x = Triangle{}
	mi := &file_triangle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Triangle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Triangle) ProtoMessage() {}

func (x *Triangle) ProtoReflect() protoreflect.Message {
	mi := &file_triangle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Triangle.ProtoReflect.Descriptor instead.
func (*Triangle) Descriptor() ([]byte, []int) {
	return file_triangle_proto_rawDescGZIP(), []int{1}
}

func (x *Triangle) GetP1() *Point {
	if x != nil {
		return x.P1
	}
	return nil
}

func (x *Triangle) GetP2() *Point {
	if x != nil {
		return x.P2
	}
	return nil
}

func (x *Triangle) GetP3() *Point {
	if x != nil {
		return x.P3
	}
	return nil
}

type TriangleCollection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Triangles     []*Triangle            `protobuf:"bytes,1,rep,name=triangles,proto3" json:"triangles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriangleCollection) Reset() {
	*x = TriangleCollection{}
	mi := &file_triangle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriangleCollection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriangleCollection) ProtoMessage() {}

func (x *TriangleCollection) ProtoReflect() protoreflect.Message {
	mi := &file_triangle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriangleCollection.ProtoReflect.Descriptor instead.
func (*TriangleCollection) Descriptor() ([]byte, []int) {
	return file_triangle_proto_rawDescGZIP(), []int{2}
}

func (x *TriangleCollection) GetTriangles() []*Triangle {
	if x != nil {
		return x.Triangles
	}
	return nil
}

var File_triangle_proto protoreflect.FileDescriptor

var file_triangle_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x74, 0x72, 0x69, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x23, 0x0a, 0x05, 0x50, 0x6f, 0x69, 0x6e, 0x74,
	0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x78, 0x12, 0x0c,
	0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x79, 0x22, 0x64, 0x0a, 0x08,
	0x54, 0x72, 0x69, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x12, 0x1c, 0x0a, 0x02, 0x70, 0x31, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6f, 0x69,
	0x6e, 0x74, 0x52, 0x02, 0x70, 0x31, 0x12, 0x1c, 0x0a, 0x02, 0x70, 0x32, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74,
	0x52, 0x02, 0x70, 0x32, 0x12, 0x1c, 0x0a, 0x02, 0x70, 0x33, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x02,
	0x70, 0x33, 0x22, 0x43, 0x0a, 0x12, 0x54, 0x72, 0x69, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x43, 0x6f,
	0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2d, 0x0a, 0x09, 0x74, 0x72, 0x69, 0x61,
	0x6e, 0x67, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x72, 0x69, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x52, 0x09, 0x74, 0x72,
	0x69, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x73, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_triangle_proto_rawDescOnce sync.Once
	file_triangle_proto_rawDescData = file_triangle_proto_rawDesc
)

func file_triangle_proto_rawDescGZIP() []byte {
	file_triangle_proto_rawDescOnce.Do(func() {
		file_triangle_proto_rawDescData = protoimpl.X.CompressGZIP(file_triangle_proto_rawDescData)
	})
	return file_triangle_proto_rawDescData
}

var file_triangle_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_triangle_proto_goTypes = []any{
	(*Point)(nil),              // 0: proto.Point
	(*Triangle)(nil),           // 1: proto.Triangle
	(*TriangleCollection)(nil), // 2: proto.TriangleCollection
}
var file_triangle_proto_depIdxs = []int32{
	0, // 0: proto.Triangle.p1:type_name -> proto.Point
	0, // 1: proto.Triangle.p2:type_name -> proto.Point
	0, // 2: proto.Triangle.p3:type_name -> proto.Point
	1, // 3: proto.TriangleCollection.triangles:type_name -> proto.Triangle
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_triangle_proto_init() }
func file_triangle_proto_init() {
	if File_triangle_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_triangle_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_triangle_proto_goTypes,
		DependencyIndexes: file_triangle_proto_depIdxs,
		MessageInfos:      file_triangle_proto_msgTypes,
	}.Build()
	File_triangle_proto = out.File
	file_triangle_proto_rawDesc = nil
	file_triangle_proto_goTypes = nil
	file_triangle_proto_depIdxs = nil
}
